services:
  - docker

script:
  - docker build --build-arg RELEASE="$LEKTOR_VERSION" -t softinstigate/lektor .
  - docker tag softinstigate/lektor:latest softinstigate/lektor:"$LEKTOR_VERSION";

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
      docker push softinstigate/lektor:$LEKTOR_VERSION;
      docker push softinstigate/lektor:latest;
    fi

env:
  global:
    # Update LEKTOR_VERSION when a new version of Lektor is released
    - LEKTOR_VERSION=3.1.3
