services:
  - docker

script:
  - docker build --build-arg RELEASE=$LEKTOR_VERSION -t softinstigate/lektor:$LEKTOR_VERSION .

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then 
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
      docker push softinstigate/lektor:$LEKTOR_VERSION;
    fi

env:
  global:
    - secure: s1ZXhCmGzJkbcefnYmCos/qVew819omMI6KjCNoTTsXH7QNdlXpD3jDar/RC+6WzOy5xLaRBPD1vjEJYSFKC37pTxewjFVYW2dH35ok+QJfL9/fiAXRgHS2sqwYF31VeIfDzQtf7VA1TtmWZRr9h7UqiKxzEpYaX6oJ1nYjscgeQKD81qJFbF80o8sCDBF+o8G+UFlspeK01BlYQemdiFNAcBGFuhzSlkWEYSHRLsbnLOKcstVbUPStQ5I1Gt+xDapUqi3hHBjnFo4e0nZxhypQ3StZjkjeer3aYioa2roaNc/SHd5C2rb9kY/YiQPjCAJ2Iy94n3r/ZoArftEC5f2Db4XVML4dP1xdWSbyvZ7CUxu+QwDpR3I3YIJIijBwD0w+DsCQ5puqc2ZtsftkvQdrMyiQTksiaqqMOFSSbdqT/39D+e/xR491OzXW4GPO3OVaVYiZ3YnTQV6LJdkb7EXYS3T3zfB/EPff5XyIAuiedvQAcQrP+LLpzSLBQk/ojCXPW7K2ZmkGr4jlq2uKWIocwL3U/+bziYeoeIEjwLKi5R6VqZRnbGUwV61x/zE/giJygWENGCgmw51p7tugK1emKIjuap4ogDHehJ2kEUvnE7nP/nVJ19z5hKyic3qzlRExpYBqX2TgXaehZUdd/kK/sXErsFO9q7clOVi6zqjM=
    - secure: CFrnH+gN77TkwSR+IuGV4No7sd4SAbkR3cd3mZ91y/GJ5Lqyx5Neps6ffjXGbjGTKUb189tn/GyvI0eqisR2z8PsZC7hiMu8z75DNvgBGDQDPhk9fLNVCfhByv3/UqaHhSBFDsjUL9BYSuba/991DwI675l0ZTRwlfDKnZH3AxQT+dy65W7PL2X1OyelvpNsIDB6y5Vch1JdEsuRafWmUigmaKZMfbA8Z3HnPp968BZ6Lb7SnlkrZvt+zTfgE4Fp/R71WuA2FXBn6ZWwoRGLzDr6JrsnDZFSE5hiKmaq60XW/n/HaXB2yM4Xx0QS9qk+84p9VZGsfik8gEc6a9Ug87SuY2nA++lGJmbOaqqU65rVj+5xxUc+A0uI63wCsPxtUwJ/ppBxer00yDfy36PmRf8bZAKs6yek3ySb5tlS0jWtfnN67LN/xzi518wfoIb4OIFAdZ35XRk3JVNi6q+VmRSTZ6hMlbO8hDW5W+JUQRPqofQr148InrUeNYqQ0sEFHZv6ZSItl1oBFi65FIt81CTv4Ix6I+tQe0MxLvMXaIX2l9wmcCCthYaGYf85OUxI/RpF8Ub/sED9VXVKaHxGysoNq7sOCyn2m2YJ/q22Box0Uxps8R2+XEERFrmNuYgLyParI8bOf9R5+GHaqW7Uei2Wz/GBMW0+a/YxbMfLUps=
  matrix:
    - LEKTOR_VERSION=3.1.2