services:
  - docker

script:
  - docker build -t softinstigate/lektor .

after_success:
   - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
     docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
     docker push softinstigate/lektor:latest
     docker tag softinstigate/lektor:latest softinstigate/lektor:$LEKTOR_VERSION
     docker push softinstigate/lektor:$LEKTOR_VERSION
     fi  

env:
  global:
    - LEKTOR_VERSION=2.3 
    - secure: t4tS+6EAC9nuE9SOKMfooux34usyPY2oBt0/737A2o9y3LXgy/jt0hyx09W4Gc1ZHq8QYoEiwHU40rlo2KWcxPKK/e4U/dZ1ne5OBJLKt5dhGr/PwaO0rVa7039zgQRn1VN+ayx92AfQCZMyA7iTrVDrM/2lxvDww0UYyZmViaA=
    - secure: NJiw/JRqiwYkEx2eisu5yllgX6oKJwhV60SldnlpnHqWzOaqXoqsKLOiP18cBPeLT6BuVYT9Z0PyaI9+2bPzt2IUC6vKuhimPYA0IRqoDfAcdSKa/Q1LcbLdbX+T941IE0iPlVesh3iFf41Cc5BM5ND2fu/yRlAHOcJFTdSqGAs=